falco:
  image:
    repo: mattjcontainerregistry/falco
    tag: 0.31.1
  serviceAccount:
    name: falco-sa
  priority: debug
  exporter:
    image: "mattjcontainerregistry/falco-exporter:v0.7.0"

metrics:
  image: "gke.gcr.io/prometheus-to-sd:v0.11.1-gke.1"
  exporter:
    enabled: true