---
# Source: falco-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-exporter-svc
  annotations:
    prometheus.io/port: "9376"
    prometheus.io/scrape: "true"
  labels:
    app: {{ template "falco.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 9376
      targetPort: 9376
      protocol: TCP
      name: metrics
  selector:
    app: {{ template "falco.fullname" . }}