apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.falco.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "falco.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

